# This workflow will install dependencies and run tests
#
# More information on:
# - https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # NOTE:
        # - ubuntu-16.04 is not being supported by Github.
        #   https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/
        os: [18.04, 20.04, 22.04, latest]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: |
        docker build --build-arg UBUNTU=${{ matrix.os }} --build-arg PYTHON=${{ matrix.python-version }} -t batspp-dev -f- . <Dockerfile
    - name: Run tests and generate coverage report
      run: |
        docker run --entrypoint './tools/run_tests.bash' --rm --mount type=bind,source="$(pwd)",target=/home/batspp batspp-dev
