# This workflow will install dependencies and run tests
#
# More information on:
# - https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: tests

on: [pull_request, push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [latest]
        python-version: [3.10.13, ]

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: |
        docker build --build-arg --build-arg PYTHON_VERSION=${{ matrix.python-version }} -t batspp-dev -f- . <Dockerfile
    - name: Run tests and generate coverage report
      run: |
        docker run --entrypoint './tools/run_tests.bash' --rm --mount type=bind,source="$(pwd)",target=/home/batspp batspp-dev
