# This workflow will install dependencies and run tests
#
# More information on:
#     https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r ./requirements.txt
        npm install -g bats
    - name: Run tests
      run: |
        coverage run -m unittest discover ./tests/
        coverage xml
